download_dir : /Users/jyesselm/BaseSpace 
analysis_dir : /Users/jyesselm/sequence_analysis 
analysis_summary_dir : /Users/jyesselm/Dropbox/data/sequencing_analysis 
seq_path : /Users/jyesselm/gdrive/sequences_and_oligos
backup_fastq_gzs : False
